default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: storage/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: storage/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("PG_DATABASE") { "your_production_db_name" } %>
  username: <%= ENV.fetch("PG_USERNAME") { "your_production_db_user" } %>
  password: <%= ENV.fetch("PG_PASSWORD") { "your_production_db_password" } %>
  host: <%= ENV.fetch("PG_HOST") { "your_production_db_host" } %>
  port: <%= ENV.fetch("PG_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
